# Generated by Django 4.1.7 on 2023-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_email", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(default="First Name", max_length=50),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
