# Generated by Django 4.1.7 on 2023-03-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_email", "0002_contact_first_name_contact_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.CharField(max_length=200),
        ),
    ]
