# Generated by Django 4.1.7 on 2023-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_email", "0004_alter_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
    ]
