# Generated by Django 4.1.7 on 2023-03-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_email", "0005_alter_contact_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="send_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
